export const CATEGORY_MAP: Record<string, string> = {
    // Root Categories
    'adap-org': '적응 및 조직 시스템',
    'alg-geom': '대수기하학',
    'astro-ph': '천체물리학',
    'atom-ph': '원자물리학',
    'chao-dyn': '카오스 역학',
    'chem-ph': '화학물리학',
    'cmp-lg': '계산 및 언어',
    'cond-mat': '응집물질물리학',
    'cs': '컴퓨터 과학',
    'dg-ga': '미분기하학 및 기하해석',
    'econ': '경제학',
    'eess': '전기전자 및 시스템공학',
    'gr-qc': '일반상대성이론 및 양자우주론',
    'hep-ex': '고에너지물리학-실험',
    'hep-lat': '고에너지물리학-격자이론',
    'hep-ph': '고에너지물리학-현상론',
    'hep-th': '고에너지물리학-이론',
    'math': '수학',
    'math-ph': '수리물리학',
    'mtrl-th': '재료이론',
    'nlin': '비선형과학',
    'nucl-ex': '핵물리학-실험',
    'nucl-th': '핵물리학-이론',
    'physics': '물리학',
    'q-alg': '양자대수학',
    'q-bio': '정량생물학',
    'q-fin': '계량금융학',
    'quant-ph': '양자물리학',
    'solv-int': '가해적분계',
    'stat': '통계학',

    // Subcategories
    'astro-ph.CO': '우주론 및 비은하 천체물리학',
    'astro-ph.EP': '지구 및 행성 천체물리학',
    'astro-ph.GA': '은하 천체물리학',
    'astro-ph.HE': '고에너지 천체물리학 현상',
    'astro-ph.IM': '관측기기 및 방법론',
    'astro-ph.SR': '태양 및 항성 천체물리학',
    'cond-mat.dis-nn': '무질서 및 신경망',
    'cond-mat.mes-hall': '메조스코픽 시스템 및 양자 홀 효과',
    'cond-mat.mtrl-sci': '재료과학',
    'cond-mat.other': '기타 응집물질',
    'cond-mat.quant-gas': '양자 기체',
    'cond-mat.soft': '소프트 응집물질',
    'cond-mat.stat-mech': '통계역학',
    'cond-mat.str-el': '강상관 전자계',
    'cond-mat.supr-con': '초전도',
    'cs.AI': '인공지능',
    'cs.AR': '하드웨어 아키텍처',
    'cs.CC': '계산복잡도',
    'cs.CE': '계산공학, 금융 및 과학',
    'cs.CG': '계산기하학',
    'cs.CL': '계산 및 언어',
    'cs.CR': '암호학 및 보안',
    'cs.CV': '컴퓨터 비전 및 패턴인식',
    'cs.CY': '컴퓨터와 사회',
    'cs.DB': '데이터베이스',
    'cs.DC': '분산, 병렬 및 클러스터 컴퓨팅',
    'cs.DL': '디지털 라이브러리',
    'cs.DM': '이산수학',
    'cs.DS': '자료구조 및 알고리즘',
    'cs.ET': '신기술',
    'cs.FL': '형식언어 및 오토마타 이론',
    'cs.GL': '일반 문헌',
    'cs.GR': '그래픽스',
    'cs.GT': '컴퓨터과학 및 게임이론',
    'cs.HC': '인간-컴퓨터 상호작용',
    'cs.IR': '정보검색',
    'cs.IT': '정보이론',
    'cs.LG': '기계학습',
    'cs.LO': '논리학',
    'cs.MA': '멀티에이전트 시스템',
    'cs.MM': '멀티미디어',
    'cs.MS': '수학 소프트웨어',
    'cs.NA': '수치해석',
    'cs.NE': '신경 및 진화 컴퓨팅',
    'cs.NI': '네트워킹 및 인터넷 아키텍처',
    'cs.OH': '기타 컴퓨터과학',
    'cs.OS': '운영체제',
    'cs.PF': '성능',
    'cs.PL': '프로그래밍 언어',
    'cs.RO': '로봇공학',
    'cs.SC': '기호계산',
    'cs.SD': '소리',
    'cs.SE': '소프트웨어공학',
    'cs.SI': '사회 및 정보 네트워크',
    'cs.SY': '시스템 및 제어',
    'eess.AS': '오디오 및 음성 처리',
    'eess.IV': '영상 및 비디오 처리',
    'eess.SP': '신호처리',
    'eess.SY': '시스템 및 제어',
    'math.AC': '가환대수',
    'math.AG': '대수기하학',
    'math.AP': '해석학',
    'math.AT': '대수적 위상수학',
    'math.CA': '고전해석학 및 미분방정식',
    'math.CO': '조합론',
    'math.CT': '범주론',
    'math.CV': '복소변수',
    'math.DG': '미분기하학',
    'math.DS': '역학계',
    'math.FA': '함수해석학',
    'math.GM': '일반수학',
    'math.GN': '일반위상수학',
    'math.GR': '군론',
    'math.GT': '기하학적 위상수학',
    'math.HO': '수학사 및 개관',
    'math.IT': '정보이론',
    'math.KT': 'K-이론 및 호몰로지',
    'math.LO': '논리학',
    'math.MG': '거리공간 기하학',
    'math.MP': '수리물리학',
    'math.NA': '수치해석',
    'math.NT': '정수론',
    'math.OA': '작용소대수',
    'math.OC': '최적화 및 제어',
    'math.PR': '확률론',
    'math.QA': '양자대수',
    'math.RA': '환 및 대수',
    'math.RT': '표현론',
    'math.SG': '심플렉틱 기하학',
    'math.SP': '스펙트럼 이론',
    'math.ST': '통계이론',
    'nlin.AO': '적응 및 자기조직화 시스템',
    'nlin.CD': '카오스 역학',
    'nlin.CG': '셀룰러 오토마타 및 격자 기체',
    'nlin.PS': '패턴 형성 및 솔리톤',
    'nlin.SI': '정확히 풀리는 및 적분가능 시스템',
    'physics.acc-ph': '가속기물리학',
    'physics.ao-ph': '대기 및 해양물리학',
    'physics.app-ph': '응용물리학',
    'physics.atm-clus': '원자 및 분자 클러스터',
    'physics.atom-ph': '원자물리학',
    'physics.bio-ph': '생물물리학',
    'physics.chem-ph': '화학물리학',
    'physics.class-ph': '고전물리학',
    'physics.comp-ph': '계산물리학',
    'physics.data-an': '데이터 분석, 통계 및 확률',
    'physics.ed-ph': '물리교육',
    'physics.flu-dyn': '유체역학',
    'physics.gen-ph': '일반물리학',
    'physics.geo-ph': '지구물리학',
    'physics.hist-ph': '물리학사 및 철학',
    'physics.ins-det': '관측기기 및 검출기',
    'physics.med-ph': '의학물리학',
    'physics.optics': '광학',
    'physics.plasm-ph': '플라즈마물리학',
    'physics.pop-ph': '대중물리학',
    'physics.soc-ph': '물리학 및 사회',
    'physics.space-ph': '우주물리학',
    'q-bio.BM': '생체분자',
    'q-bio.CB': '세포생물학',
    'q-bio.GN': '유전체학',
    'q-bio.MN': '분자 네트워크',
    'q-bio.NC': '신경 및 인지',
    'q-bio.OT': '기타 정량생물학',
    'q-bio.PE': '집단 및 진화',
    'q-bio.QM': '정량적 방법론',
    'q-bio.SC': '하위세포 과정',
    'q-bio.TO': '조직 및 기관',
    'q-fin.CP': '계산금융',
    'q-fin.EC': '경제학',
    'q-fin.GN': '일반금융',
    'q-fin.MF': '수리금융',
    'q-fin.PM': '포트폴리오 관리',
    'q-fin.PR': '가격결정 및 위험관리',
    'q-fin.RM': '위험관리',
    'q-fin.ST': '통계금융',
    'q-fin.TR': '거래 및 시장 미시구조',
    'stat.AP': '응용통계',
    'stat.CO': '계산통계',
    'stat.ME': '통계방법론',
    'stat.ML': '기계학습',
    'stat.OT': '기타 통계학',
    'stat.TH': '통계이론',
};

export const getCategoryName = (code?: string): string => {
    if (!code) return '';

    // 1. Exact match (Root or Subcategory)
    if (CATEGORY_MAP[code]) {
        return CATEGORY_MAP[code];
    }

    // 2. Fallback: "Category (code)" if prefix matches
    const prefix = code.split('.')[0];
    if (CATEGORY_MAP[prefix]) {
        return `${CATEGORY_MAP[prefix]} (${code})`;
    }

    // 3. No match
    return code;
};
